#!/usr/bin/env bash
SCRIPTPATH="$(
  cd "$(dirname "$0")"
  pwd -P
)"

#down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s $SCRIPTPATH/down /tmp/leftwm-theme-down

# check if dunst is installed and if it is, run it
if command -v dunst; then
  if pgrep dunst; then
    pkill dunst
  fi
  dunst -conf $SCRIPTPATH/dunstrc &
fi

#boot picom if it exists
if command -v picom; then
  if [ $(cat /sys/class/power_supply/BAT0/status) = 'Discharging' ]; then
    picom --config $SCRIPTPATH/picom.conf --backend xrender &>/dev/null &
  else
    picom --config $SCRIPTPATH/picom.conf --experimental-backends &>/dev/null &
  fi
fi

# set background
#  if [ -x "$(command -v feh)" ]; then
#    feh --bg-fill "$SCRIPTPATH"/nord-wallpaper.jpg
#  fi

#set the theme.toml config
leftwm-command "LoadTheme $SCRIPTPATH/theme.toml"

#boot polybar based on the number of monitors found
if command -v polybar; then
  pkill polybar
  monitors="$(polybar -m | sed s/:.*// | tac)"
  while read -r display; do
    MONITOR=$display polybar --config=$SCRIPTPATH/polybar.ini mainbar &>/dev/null &
  done <<<"$monitors"
  exit 0
fi
